import { AuthContextProvider } from "../_utils/auth";
import { TokenProvider } from "@/_utils/token-context";
import { AlbumProvider } from "../_utils/album-context";
import Header from "./components/header/header";
import localFont from "next/font/local";
import "./globals.css";
import { UserContextProvider } from "@/_utils/user-context";

const geistSans = localFont({
    src: "/fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "/fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "EchoRate",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="h-screen bg-vinyl">
            {/* <body className="bg-scroll bg-gradient-to-t from-zinc-950 to-zinc-700 h-full min-h-screen "> */}
                <AuthContextProvider>
                    <UserContextProvider>
                        <TokenProvider>
                            <AlbumProvider>
                                <Header />
                                <div className="w-7/12 my-0 mx-auto py-10">
                                    {children}
                                </div>
                            </AlbumProvider>
                        </TokenProvider>
                    </UserContextProvider>
                </AuthContextProvider>
            </body>
        </html>
    );
}
